import * as schema from '@/db/schema';

type HabitDefinition = typeof schema.habitDefinitions.$inferSelect;

export const PREDEFINED_HABITS: Omit<HabitDefinition, 'isActive'>[] = [
  // Health & Hygiene
  {
    id: 'tummy_time',
    category: 'health',
    iconName: 'Baby',
    labelKey: 'habit.tummyTime.label',
    descriptionKey: 'habit.tummyTime.description',
    minAgeMonths: 0,
    maxAgeMonths: 6,
    defaultFrequency: 'daily',
    sortOrder: 1,
  },
  {
    id: 'brushing_teeth',
    category: 'health',
    iconName: 'Sparkles',
    labelKey: 'habit.brushingTeeth.label',
    descriptionKey: 'habit.brushingTeeth.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'twice_daily',
    sortOrder: 2,
  },
  {
    id: 'bath_time',
    category: 'health',
    iconName: 'Bath',
    labelKey: 'habit.bathTime.label',
    descriptionKey: 'habit.bathTime.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 3,
  },
  {
    id: 'hand_washing',
    category: 'health',
    iconName: 'HandMetal',
    labelKey: 'habit.handWashing.label',
    descriptionKey: 'habit.handWashing.description',
    minAgeMonths: 12,
    maxAgeMonths: null,
    defaultFrequency: 'multiple_daily',
    sortOrder: 4,
  },
  {
    id: 'diaper_free_time',
    category: 'health',
    iconName: 'Sun',
    labelKey: 'habit.diaperFreeTime.label',
    descriptionKey: 'habit.diaperFreeTime.description',
    minAgeMonths: 0,
    maxAgeMonths: 24,
    defaultFrequency: 'daily',
    sortOrder: 5,
  },
  {
    id: 'sunscreen',
    category: 'health',
    iconName: 'SunMedium',
    labelKey: 'habit.sunscreen.label',
    descriptionKey: 'habit.sunscreen.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 6,
  },

  // Learning & Development
  {
    id: 'reading_time',
    category: 'learning',
    iconName: 'BookOpen',
    labelKey: 'habit.readingTime.label',
    descriptionKey: 'habit.readingTime.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 1,
  },
  {
    id: 'singing_music',
    category: 'learning',
    iconName: 'Music',
    labelKey: 'habit.singingMusic.label',
    descriptionKey: 'habit.singingMusic.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 2,
  },
  {
    id: 'talking_conversation',
    category: 'learning',
    iconName: 'MessageCircle',
    labelKey: 'habit.talkingConversation.label',
    descriptionKey: 'habit.talkingConversation.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'multiple_daily',
    sortOrder: 3,
  },
  {
    id: 'peek_a_boo',
    category: 'learning',
    iconName: 'Eye',
    labelKey: 'habit.peekABoo.label',
    descriptionKey: 'habit.peekABoo.description',
    minAgeMonths: 3,
    maxAgeMonths: 18,
    defaultFrequency: 'daily',
    sortOrder: 4,
  },
  {
    id: 'counting_practice',
    category: 'learning',
    iconName: 'Hash',
    labelKey: 'habit.countingPractice.label',
    descriptionKey: 'habit.countingPractice.description',
    minAgeMonths: 18,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 5,
  },
  {
    id: 'color_shape_learning',
    category: 'learning',
    iconName: 'Shapes',
    labelKey: 'habit.colorShapeLearning.label',
    descriptionKey: 'habit.colorShapeLearning.description',
    minAgeMonths: 18,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 6,
  },
  {
    id: 'puzzle_time',
    category: 'learning',
    iconName: 'Puzzle',
    labelKey: 'habit.puzzleTime.label',
    descriptionKey: 'habit.puzzleTime.description',
    minAgeMonths: 12,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 7,
  },
  {
    id: 'sensory_play',
    category: 'learning',
    iconName: 'Fingerprint',
    labelKey: 'habit.sensoryPlay.label',
    descriptionKey: 'habit.sensoryPlay.description',
    minAgeMonths: 3,
    maxAgeMonths: 36,
    defaultFrequency: 'daily',
    sortOrder: 8,
  },

  // Physical Activity
  {
    id: 'outdoor_play',
    category: 'physical',
    iconName: 'TreePine',
    labelKey: 'habit.outdoorPlay.label',
    descriptionKey: 'habit.outdoorPlay.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 1,
  },
  {
    id: 'dance_movement',
    category: 'physical',
    iconName: 'Music2',
    labelKey: 'habit.danceMovement.label',
    descriptionKey: 'habit.danceMovement.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 2,
  },
  {
    id: 'ball_play',
    category: 'physical',
    iconName: 'Circle',
    labelKey: 'habit.ballPlay.label',
    descriptionKey: 'habit.ballPlay.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 3,
  },
  {
    id: 'walking_practice',
    category: 'physical',
    iconName: 'Footprints',
    labelKey: 'habit.walkingPractice.label',
    descriptionKey: 'habit.walkingPractice.description',
    minAgeMonths: 9,
    maxAgeMonths: 18,
    defaultFrequency: 'daily',
    sortOrder: 4,
  },
  {
    id: 'stretching',
    category: 'physical',
    iconName: 'Stretch',
    labelKey: 'habit.stretching.label',
    descriptionKey: 'habit.stretching.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 5,
  },

  // Sleep & Routine
  {
    id: 'bedtime_routine',
    category: 'sleep',
    iconName: 'Moon',
    labelKey: 'habit.bedtimeRoutine.label',
    descriptionKey: 'habit.bedtimeRoutine.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 1,
  },
  {
    id: 'wake_up_routine',
    category: 'sleep',
    iconName: 'Sunrise',
    labelKey: 'habit.wakeUpRoutine.label',
    descriptionKey: 'habit.wakeUpRoutine.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 2,
  },
  {
    id: 'nap_time',
    category: 'sleep',
    iconName: 'CloudMoon',
    labelKey: 'habit.napTime.label',
    descriptionKey: 'habit.napTime.description',
    minAgeMonths: 0,
    maxAgeMonths: 36,
    defaultFrequency: 'daily',
    sortOrder: 3,
  },
  {
    id: 'wind_down_time',
    category: 'sleep',
    iconName: 'Clock',
    labelKey: 'habit.windDownTime.label',
    descriptionKey: 'habit.windDownTime.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 4,
  },

  // Social & Emotional
  {
    id: 'eye_contact',
    category: 'social',
    iconName: 'Eye',
    labelKey: 'habit.eyeContact.label',
    descriptionKey: 'habit.eyeContact.description',
    minAgeMonths: 0,
    maxAgeMonths: 12,
    defaultFrequency: 'multiple_daily',
    sortOrder: 1,
  },
  {
    id: 'cuddling_bonding',
    category: 'social',
    iconName: 'Heart',
    labelKey: 'habit.cuddlingBonding.label',
    descriptionKey: 'habit.cuddlingBonding.description',
    minAgeMonths: 0,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 2,
  },
  {
    id: 'greeting_practice',
    category: 'social',
    iconName: 'Hand',
    labelKey: 'habit.greetingPractice.label',
    descriptionKey: 'habit.greetingPractice.description',
    minAgeMonths: 12,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 3,
  },
  {
    id: 'sharing_practice',
    category: 'social',
    iconName: 'Users',
    labelKey: 'habit.sharingPractice.label',
    descriptionKey: 'habit.sharingPractice.description',
    minAgeMonths: 18,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 4,
  },
  {
    id: 'thank_you_manners',
    category: 'social',
    iconName: 'ThumbsUp',
    labelKey: 'habit.thankYouManners.label',
    descriptionKey: 'habit.thankYouManners.description',
    minAgeMonths: 18,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 5,
  },
  {
    id: 'playdates',
    category: 'social',
    iconName: 'UsersRound',
    labelKey: 'habit.playdates.label',
    descriptionKey: 'habit.playdates.description',
    minAgeMonths: 12,
    maxAgeMonths: null,
    defaultFrequency: 'weekly',
    sortOrder: 6,
  },

  // Nutrition
  {
    id: 'water_drinking',
    category: 'nutrition',
    iconName: 'Droplets',
    labelKey: 'habit.waterDrinking.label',
    descriptionKey: 'habit.waterDrinking.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'multiple_daily',
    sortOrder: 1,
  },
  {
    id: 'vegetable_tasting',
    category: 'nutrition',
    iconName: 'Carrot',
    labelKey: 'habit.vegetableTasting.label',
    descriptionKey: 'habit.vegetableTasting.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 2,
  },
  {
    id: 'family_meals',
    category: 'nutrition',
    iconName: 'UtensilsCrossed',
    labelKey: 'habit.familyMeals.label',
    descriptionKey: 'habit.familyMeals.description',
    minAgeMonths: 6,
    maxAgeMonths: null,
    defaultFrequency: 'daily',
    sortOrder: 3,
  },
  {
    id: 'self_feeding',
    category: 'nutrition',
    iconName: 'HandPlatter',
    labelKey: 'habit.selfFeeding.label',
    descriptionKey: 'habit.selfFeeding.description',
    minAgeMonths: 9,
    maxAgeMonths: 36,
    defaultFrequency: 'daily',
    sortOrder: 4,
  },
];
